module.exports = {
  'secret': 'wdr-super-secret-key',
  ROLEs: ['OC', 'OBSERVER','MANAGER DATA','SENIOR ZONAL OFFICER','ZONAL OFFICER','SENIOR DATA OFFICER','DATA OFFICER','WEATHER FORECASTER','MANAGER STATION NETWORKS','WEATHER ANALYST','OBSERVE ARCHIVE']
};