export class Observationslip{
    constructor(
  public Date: string,
  public id: null,
  public Userid: number,
  public Station: number,
  public TIME: string,
  public TotalAmountOfAllClouds: number,
  public TotalAmountOfLowClouds: number,
  public TypeOfLowClouds1: number,
  public OktasOfLowClouds1: number,
  public HeightOfLowClouds1: number,
  public CLCODEOfLowClouds1: string,
  public TypeOfLowClouds2: number,
  public OktasOfLowClouds2: number,
  public HeightOfLowClouds2: number,
  public CLCODEOfLowClouds2: string,
  public TypeOfLowClouds3: number,
  public OktasOfLowClouds3: number,
  public HeightOfLowClouds3: number,
  public CLCODEOfLowClouds3: string,
  public TypeOfMediumClouds1: number,
  public OktasOfMediumClouds1: number,
  public HeightOfMediumClouds1: number,
  public CLCODEOfMediumClouds1: string,
  public TypeOfMediumClouds2: number,
  public OktasOfMediumClouds2: number,
  public HeightOfMediumClouds2: number,
  public CLCODEOfMediumClouds2: string,
  public TypeOfMediumClouds3: number,
  public OktasOfMediumClouds3: number,
  public HeightOfMediumClouds3: number,
  public CLCODEOfMediumClouds3: string,
  public TypeOfHighClouds1: number,
  public OktasOfHighClouds1: number,
  public HeightOfHighClouds1: number,
  public CLCODEOfHighClouds1: string,
  public TypeOfHighClouds2: number,
  public OktasOfHighClouds2: number,
  public HeightOfHighClouds2: number,
  public CLCODEOfHighClouds2: string,
  public TypeOfHighClouds3: number,
  public OktasOfHighClouds3: number,
  public HeightOfHighClouds3: number,
  public CLCODEOfHighClouds3: string,
  public CloudSearchLightReading: number,
  public Rainfall: string,
  public Dry_Bulb: string,
  public Wet_Bulb: string,
  public Max_Read: number,
  public Max_Reset: number,
  public Min_Read: number,
  public Min_Reset: number,
  public Piche_Read: number,
  public Piche_Reset: number,
  public TimeMarksThermo: number,
  public TimeMarksHygro: number,
  public TimeMarksRainRec: number,
  public Present_Weather: string,
  public Present_WeatherCode: string,
  public Past_Weather: string,
  public Past_WeatherCode:string,
  public Visibility: number,
  public Wind_Direction: string,
  public Wind_Speed: string,
  public Gusting: number,
  public AttdThermo: number,
  public PrAsRead: number,
  public Correction: number,
  public CLP: string,
  public MSLPr: number,
  public TimeMarksBarograph: number,
  public TimeMarksAnemograph: number,
  public OtherTMarks: string,
  public SoilMoisture: string,
  public SoilTemperature: string,
  public sunduration: string,
  public trend: string,
  public windrun: string,
  public Max_temp: string,
  public Min_temp: string,
  public speciormetar: string,
  public UnitOfWindSpeed: string,
  public IndOrOmissionOfPrecipitation: string,
  public TypeOfStation_Present_Past_Weather: string,
  public HeightOfLowestCloud: string,
  public StandardIsobaricSurface: string,
  public GPM: string,
  public DurationOfPeriodOfPrecipitation: string,
  public GrassMinTemp: string,
  public CI_OfPrecipitation: string,
  public BE_OfPrecipitation: string,
  public IndicatorOfTypeOfIntrumentation: string,
  public SignOfPressureChange: string,
  public Supp_Info: string,
  public VapourPressure: string,
  public T_H_Graph: string,
  public DeviceType: string,
  public SyncStatus: number,
  public O_SubmittedBy: string,
  public Remarks: string,
  public Approved: number,
  public ApprovedBy: number,
  public Endorsed: string,
  public EndorsedBy: string
    ) {}
  }

  export class Archive{
    constructor(
      public Date: string,
      public station: string,
      public StationNumber: string,
      public AR_SubmittedBy: string,
      public Approved: string,
      public Rainfall: string,
      public Username: string

    ){}
  }

  export class Dekandal{
    constructor(
     public Date: string,
     public station: string,
     public MAX_TEMP: string,
     public MIN_TEMP: string,
     public DRY_BULB_0600Z: string,
     public WET_BULB_0600Z: string,
     public DEW_POINT_0600Z: string,
     public RELATIVE_HUMIDITY_0600Z: string,
     public WIND_DIRECTION_0600Z: string,
     public WIND_SPEED_0600Z: string,
     public RAINFALL_0600Z: string,
     public DRY_BULB_1200Z: string,
     public WET_BULB_1200Z: string,
     public DEW_POINT_1200Z: string,
     public RELATIVE_HUMIDITY_1200Z: string,
     public WIND_DIRECTION_1200Z: string,
     public WIND_SPEED_1200Z: string,
     public AD_SubmittedBy: string,
     public Approved: string
    ){}
  }

  export class Synoptic{
    constructor(
      public  Date: string, 
      public  station: string, 
      public  TIME: string, 
      public  UWS: string, 
      public  BN: string, 
      public  IOOP: string,
      public  TSPPW: string, 
      public  HLC: string, 
      public  HV: string, 
      public  TCC: string, 
      public  WD: string, 
      public  WS: string, 
      public  GI1_1: string, 
      public  SignOfData_1: string,
      public  Air_temperature: string,
      public  GI2_1: string, 
      public  SignOfData_2: string, 
      public  Dewpoint_temperature: string, 
      public  GI3_1: string, 
      public  PASL: string, 
      public  GI4_1: string, 
      public  SIS: string, 
      public  GSIS: string, 
      public  GI6_1: string, 
      public  AOP: string, 
      public  DPOP: string, 
      public  GI7_1: string, 
      public  Present_Weather: string, 
      public  Past_Weather: string, 
      public  GI8_1: string, 
      public  AOC: string, 
      public  CLOG: string, 
      public  CGOG: string, 
      public  CHOG: string, 
      public  Section_Indicator333: string, 
      public  GI0_1: string, 
      public  GMT: string, 
      public  CIOP: string, 
      public  BEOP: string, 
      public  ThunderStorm: string, 
      public  HailStorm: string, 
      public  Fog: string, 
      public  EarthQuake: string, 
      public  Anemometer_Reading: string, 
      public  Actual_Rainfall: string, 
      public  GI1_2: string, 
      public  SignOfData_3: string, 
      public  Max_TempTx: string, 
      public  GI2_2: string, 
      public  SignOfData_4: string, 
      public  Max_TempTn: string, 
      public  GI5_1: string, 
      public  AOE: string, 
      public  ITI: string, 
      public  GI55: string, 
      public  DOS: string, 
      public  GI5_2: string, 
      public  SPC: string, 
      public  PCI24Hrs: string, 
      public  GI6_2: string,
      public  AOP_2: string, 
      public  DPOP_2: string, 
      public  GI8_2: string, 
      public  AICL: string, 
      public  GOC: string, 
      public  HBCLOM: string, 
      public  GI8_3: string, 
      public  AICL_2: string, 
      public  GOC_2: string, 
      public  HBCLOM_2: string, 
      public  GI8_4: string, 
      public  AICL_3: string, 
      public  GOC_3: string, 
      public  HBCLOM_3: string, 
      public  GI8_5: string, 
      public  AICL_4: string, 
      public  GOC_4: string, 
      public  HBCLOM_4: string, 
      public  GI9: string, 
      public  Supp_Info: string,
      public  Section_Indicator555: string, 
      public  GI1_3: string, 
      public  SignOfData_5: string, 
      public  Wetbulb_Temp: string, 
      public  R_Humidity: string,
      public  V_Pressure: string, 
      public  remarks: string,
      public  time_: string, 
      public  ObserverOnDuty: string, 
      public  to_: string, 
      public  from_: string, 
      public  Approved: string, 
      public  AS_SubmittedBy: string,
){}
}
 
export class Metar{
  constructor(
    public  Date: string, 
    public  station: string, 
    public  TIME: string, 
    public  METARSPECI: string, 
    public  CCCC: string, 
    public  YYGGgg: string, 
    public  Dddfffmfm: string, 
    public  WWorCAVOK: string, 
    public  W1W1: string, 
    public  NlCCNmCCNhCC: string, 
    public  TTTdTd: string, 
    public  Qnhhpa: string, 
    public  Qnhin: string, 
    public  Qfehpa: string, 
    public  Qfein: string, 
    public  REW1W1: string, 
    public  AM_SubmittedBy: string, 
    public  Approved: string,

  ){}

}

export class Weathersummary{
  constructor(
    public  Date: string, 
    public  station: string, 
    public  TEMP_MAX: string, 
    public  TEMP_MIN: string, 
    public  SUNSHINE: string, 
    public  DB_0600Z: string, 
    public  WB_0600Z: string, 
    public  DP_0600Z: string, 
    public  VP_0600Z: string, 
    public  RH_0600Z: string, 
    public  CLP_0600Z: string, 
    public  GPM_0600Z: string, 
    public  WIND_DIR_0600Z: string, 
    public  FF_0600Z: string, 
    public  DB_1200Z: string, 
    public  WB_1200Z: string, 
    public  DP_1200Z: string, 
    public  VP_1200Z: string, 
    public  RH_1200Z: string, 
    public  CLP_1200Z: string, 
    public  GPM_1200Z: string, 
    public  WIND_DIR_1200Z: string, 
    public  FF_1200Z: string, 
    public  WIND_RUN: string, 
    public  R_F: string, 
    public  ThunderStorm: string, 
    public  Fog: string, 
    public  Haze: string, 
    public  HailStorm: string,
    public  EarthQuake: string, 
    public  AW_SubmittedBy: string, 
    public  Approved: string,
  ){}
}

export class Observe{
  constructor(
    public  Date: string, 
    public  station: string, 
    public  TIME: string, 
    public  TotalAmountOfAllClouds: string, 
    public  TotalAmountOfLowClouds: string, 
    public  TypeOfLowClouds1: string, 
    public  OktasOfLowClouds1: string, 
    public  HeightOfLowClouds1: string, 
    public  CLCODEOfLowClouds1: string, 
    public  TypeOfLowClouds2: string, 
    public  OktasOfLowClouds2: string, 
    public  HeightOfLowClouds2: string, 
    public  CLCODEOfLowClouds2: string, 
    public  TypeOfLowClouds3: string, 
    public  OktasOfLowClouds3: string, 
    public  HeightOfLowClouds3: string, 
    public  CLCODEOfLowClouds3: string, 
    public  TypeOfMediumClouds1: string, 
    public  OktasOfMediumClouds1: string, 
    public  HeightOfMediumClouds1: string, 
    public  CLCODEOfMediumClouds1: string, 
    public  TypeOfMediumClouds2: string, 
    public  OktasOfMediumClouds2: string, 
    public  HeightOfMediumClouds2: string, 
    public  CLCODEOfMediumClouds2: string, 
    public  TypeOfMediumClouds3: string, 
    public  OktasOfMediumClouds3: string, 
    public  HeightOfMediumClouds3: string, 
    public  CLCODEOfMediumClouds3: string, 
    public  TypeOfHighClouds1: string, 
    public  OktasOfHighClouds1: string, 
    public  HeightOfHighClouds1: string, 
    public  CLCODEOfHighClouds1: string, 
    public  TypeOfHighClouds2: string, 
    public  OktasOfHighClouds2: string, 
    public  HeightOfHighClouds2: string, 
    public  CLCODEOfHighClouds2: string, 
    public  TypeOfHighClouds3: string, 
    public  OktasOfHighClouds3: string, 
    public  HeightOfHighClouds3: string, 
    public  CLCODEOfHighClouds3: string, 
    public  CloudSearchLightReading: string, 
    public  Rainfall: string, 
    public  Dry_Bulb: string, 
    public  Wet_Bulb: string, 
    public  Max_Read: string, 
    public  Max_Reset: string, 
    public  Min_Read: string, 
    public  Min_Reset: string, 
    public  Piche_Read: string, 
    public  Piche_Reset: string, 
    public  TimeMarksThermo: string, 
    public TimeMarksHygro: string, 
    public TimeMarksRainRec: string, 
    public  Present_Weather: string, 
    public Visibility: string, 
    public  Wind_Direction: string, 
    public  Wind_Speed: string, 
    public  Gusting: string, 
    public  AttdThermo: string, 
    public  PrAsRead: string, 
    public  Correction: string, 
    public  CLP: string, 
    public  MSLPr: string, 
    public TimeMarksBarograph: string,
    public  TimeMarksAnemograph: string, 
    public  OtherTMarks: string, 
    public  Remarks: string, 
    public  AO_SubmittedBy: string, 
    public  Approved: string,
  ){}
  }
  /**
   * ARCHIVE SCANNED FORMS 
   * 
   * code for all the archive scanned forms goes here
   */
  export class Archivescanned{
    constructor(
      public  Form_scanned: string, 
      public  station: string, 
      public  year: string, 
      public  month: string, 
      public  Description: string, 
      public  FileRef: string, 
      public  SM_SubmittedBy: string, 
      public  ApprovedBy: string, 
      public  Approved: number,
    ){}
  }

  export class scannedAnnualRainfall{
    constructor(
      public  Form_scanned: string, 
      public  station: string, 
      public  year: string, 
      public  Description: string, 
      public  FileRef: string, 
      public  SY_SubmittedBy: string, 
      public  ApprovedBy: string, 
      public  Approved: number,
    ){}
  }

  export class scannedDekandal{
    constructor(
      public  station: string, 
      public  from_date: string, 
      public  to_date: string, 
      public  Description: string, 
      public  FileRef: string, 
      public  SDE_SubmittedBy: string, 
      public  ApprovedBy: string, 
      public  Approved: number,
    ){}
  }
  export class scannedMetar{
    constructor(
      public  Form_scanned: string, 
      public  station: string, 
      public  form_date: string,
      public  Description: string, 
      public  FileRef: string, 
      public  SD_SubmittedBy: string, 
      public  ApprovedBy: string, 
      public  Approved: number,
    ){}
  }
  export class scannedObservationslip{
    constructor(
      public  Form_scanned: string, 
      public  station: string, 
      public  form_date: string, 
      public  TIME: string, 
      public  Description: string, 
      public  FileRef: string, 
      public  SD_SubmittedBy: string, 
      public  ApprovedBy: string, 
      public  Approved: number,
    ){}
  }
  export class scannedSynoptic{
    constructor(
      public  Form_scanned: string,
      public  station: string, 
      public  form_date: string, 
      public  Description: string, 
      public  FileName_FirstPage: string, 
      public  FileName_SecondPage: string, 
      public  SD_SubmittedBy: string, 
      public  ApprovedBy: string, 
      public  Approved: number,
    ){}
  }
